[package]
name = "goldfish-core"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"

[dependencies]
getset = "0.0.9"
anyhow = "1.0.26"
derivative = "1.0.3"
rand = "0.7.2"
scryfall = "0.5.0"
dirs = "2.0.2"
lazy_static = "1.4.0"
serde_json = "1.0.47"
